### ISSUE TITLE
Write a "Contribution guide" section in README

### ISSUE THREAD

**Issue by Dzoukr** [Dzoukr/Dapper.FSharp#32]
After great contribution by @JordanMarr (and a tiny fuzz about PR with _include_ / _exclude_ from my side), there should be a section in README with defined contribution procedure like:

- Create Issue
- Describe desired functionality
- Discuss the impact on library
- Discuss if it's a feature or major change
- Approve / Deny
- Create PR

Major goal: Avoid future misunderstandings and do not waste anyone's good intended PR.

**Comment by JordanMarr** [comment]
That is a great idea. I really should have announced that PR before presenting it out of the blue! I will be sure to spend more time vetting everything out up front next time (as I did for the original PR). API changes always have to be very carefully considered since they can be difficult to roll back.
